services:
  llamafactory:
    build:
      dockerfile: ./docker/docker-rocm/Dockerfile
      context: ../..
      args:
        PIP_INDEX: https://pypi.tuna.tsinghua.edu.cn/simple
        EXTRAS: metrics
    container_name: llamafactory
    ports:
      - "7860:7860"
      - "8000:8000"
    ipc: host
    tty: true
    stdin_open: true
    command: bash
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri:/dev/dri
    restart: unless-stopped
    privileged: true
    volumes:  # 添加挂载卷配置 相对路径起点时yml文件所在目录
      - ./hf_cache:/root/.cache/huggingface  # 挂载 Hugging Face 缓存目录
      - ./shared_data:/app/shared_data       # 挂载共享数据目录
      - ./output:/app/output                 # 挂载输出目录
